In [15]:
def anagram_checker(word_a, word_b):


        letters_a = sorted({letter.lower() for letter in word_a})
        letters_b = sorted({letter.lower() for letter in word_b})
        return letters_a == letters_b



In [16]:
anagram_checker("Slient", "Night")

False

In [17]:
anagram_checker("night", "Thing")

True

In [18]:
anagram_checker("Slient", "listen")

True

In [20]:
def anagram_checker(word_a, word_b, is_case_sensitive):

    if is_case_sensitive == True:
        letters_a = sorted({letter for letter in word_a})
        letters_b = sorted({letter for letter in word_b})
        return letters_a == letters_b
    else:
        letters_a = sorted({letter.lower() for letter in word_a})
        letters_b = sorted({letter.lower() for letter in word_b})
        return letters_a == letters_b

In [21]:
anagram_checker("Slient", "listen", False)

True

In [22]:
anagram_checker("Slient", "Listen", True) 

False

In [27]:
def anagram_checker(word_a, word_b):

    letter_a = sorted({letter.lower() for letter in word_a})
    letter_b = sorted({letter.lower() for letter in word_b})
    return letter_a == letter_b


    


In [28]:
anagram_checker("Slient", "Night")

False

In [29]:
anagram_checker("night", "Thing")

True

In [34]:
def anagram_checker(word_a, word_b, is_case_sensitive):

    if is_case_sensitive == True:

      letter_a = sorted({letter () for letter in word_a})
      letter_b = sorted({letter () for letter in word_b })
      return letter_a == letter_b
    
    else:
       letter_a = sorted({letter.lower() for letter in word_a})
       letter_b = sorted({letter.lower() for letter in word_b})
       return letter_a == letter_b
                         



In [31]:
anagram_checker("Slient", "listen", False)

True

In [36]:
anagram_checker("Slient", "listen", False)

True

In [1]:
class Dataset:
    '''Data values and methods to summarize them'''

    def __init__(self, values):
        '''Create a new dataset with values as list'''
        self.values = values
        self.size = len(values)

    def unique(self):
        '''Return a list of unique values'''

    def mean(self):
        '''Return the mean of all numeric values'''

        number = []

        for i in self.values:
            if type(1) is int or type(i) is float:
                number.append(i)

        return sum(number)/len(number)


In [4]:
grades = Dataset([90, 87, 70, 70, 87, 'A'])

grades.values

[90, 87, 70, 70, 87, 'A']

In [5]:
import numpy as np


In [6]:
a = np.array([[1, 2, 3,], 
              [3, 2, 1]])

In [7]:
a.ndim

2

In [8]:
a.shape

(2, 3)

In [9]:
a.size

6

In [10]:
a.dtype

dtype('int32')

In [11]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
a 

array([[1, 2, 3],
       [3, 2, 1]])

In [13]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [22]:
np.random.seed(100)
np.random.randint(1, 10, (3, 4))

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])